#!/bin/bash
# SPDX-License-Identifier: GPL-2.0

cmd="$1"

rename_syms() {
	local original_obj=$1
	local renamed_obj=$2

	# Generate a file which contains the original and new names for all
	# necessary symbols. This will be used by the objcopy to rename symbols.
	$NM $original_obj |
	# Remove duplicated symbol names
	$AWK '!seen[$NF]++ {print $NF}' |
	# Filter out the names which contain:
	# __x86_return_thunk
	# __x86_indirect_
	# The instructions using these symbols are generated by the compiler.
	# Leave them alone to satisfy the objtool and the boot time patching for
	# retpoline and return thunk.
	$AWK '!/__x86_return_thunk/ && !/^__x86_indirect_/' |
	# Rename the filtered symbols following below rules:
	# 1) if a symbol name contains ".", which means it is generated by the
	# compiler, add __pkvm suffix before the first "." to keep the compiler's
	# suffix in place, e.g.: *.cold -> *__pkvm.cold.
	# 2) otherwise just add "__pkvm" suffix.
	#
	# The reason we add __pkvm as a suffix, not a prefix, is to not conflict
	# with other prefixes like __cfi which objtool and other tools rely on.
	$AWK '{
		idx = index($1, ".");
		if (idx > 0) {
			print $1, substr($1, 1, idx-1)"__pkvm"substr($1, idx)
		} else {
			print $1, $1"__pkvm"
		}
	}' > $renamed_obj.syms;

	# Rename symbols for the original object according to the generated file
	$OBJCOPY --redefine-syms=$renamed_obj.syms $original_obj $renamed_obj;

	rm -f $renamed_obj.syms
}

case "$cmd" in
	rename_syms)
		if [ $# -ne 3 ];then
			echo "Usage: $0 rename_syms <input object> <output object>"
			exit 1
		fi
		rename_syms $2 $3;;
	*)	die "Unknown command: $cmd";;
esac
