# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I $(srctree)/arch/x86/kvm
ccflags-y += -I $(srctree)/arch/x86/kvm/pkvm
# TODO: make the stack protector work with the pKVM hypervisor code
ccflags-y += -fno-stack-protector
ccflags-y += -D__PKVM_HYP__
ccflags-y += -include $(srctree)/arch/x86/kvm/pkvm/undef.h

asflags-y += -D__PKVM_HYP__
asflags-y += -include $(srctree)/arch/x86/kvm/pkvm/undef.h

cmd_deps			:= $(src)/compiling_cmds.sh

pkvm-hyp-y			:= early_alloc.o pkvm.o memory.o cpu.o \
				   idt.o entry.o init_finalize.o pgtable.o \
				   mmu.o page_alloc.o

kernel-x86-lib			:= ../../lib
pkvm-hyp-y			+= $(kernel-x86-lib)/memset_64.o

pkvm-hyp-$(CONFIG_MITIGATION_RETPOLINE)	+= retpoline.o
$(obj)/retpoline.pkvm.o: $(obj)/retpoline.pkvm.S FORCE
	$(call if_changed_rule,as_o_S)
$(obj)/retpoline.pkvm.S: $(srctree)/arch/x86/lib/retpoline.S $(cmd_deps) FORCE
	$(call if_changed,patch_retpoline)
quiet_cmd_patch_retpoline = PATCH_RETPOLINE $@
      cmd_patch_retpoline = $(BASH) $(src)/compiling_cmds.sh patch_retpoline $< $@

kernel-lib			:= ../../../../lib
pkvm-hyp-$(CONFIG_LIST_HARDENED) += $(kernel-lib)/list_debug.o

kvm				:= ..
pkvm-hyp-y			+= $(kvm)/x86.o

pkvm-hyp-$(CONFIG_PKVM_INTEL)	+= vmx/host_vmentry.o vmx/host_vmx.o \
				   $(kvm)/vmx/vmx.o vmx/idt.o

pkvm-obj 			:= $(patsubst %.o,%.pkvm.o,$(pkvm-hyp-y))
obj-$(CONFIG_PKVM_X86)		+= pkvm.o

targets += $(pkvm-obj) pkvm.tmp.o pkvm.lds retpoline.pkvm.S
clean-files += retpoline.pkvm.S

$(obj)/%.pkvm.o: $(src)/%.c FORCE
	$(call if_changed_rule,cc_o_c)
$(obj)/%.pkvm.o: $(src)/%.S FORCE
	$(call if_changed_rule,as_o_S)

$(obj)/pkvm.lds: $(src)/pkvm.lds.S FORCE
	$(call if_changed_dep,cpp_lds_S)

LDFLAGS_pkvm.tmp.o := -r -T
$(obj)/pkvm.tmp.o: $(obj)/pkvm.lds $(addprefix $(obj)/,$(pkvm-obj)) FORCE
	$(call if_changed,ld)

$(obj)/pkvm.o: $(obj)/pkvm.tmp.o $(cmd_deps) FORCE
	$(call if_changed,pkvmcopy)

quiet_cmd_pkvmcopy = PKVMPCOPY $@
      cmd_pkvmcopy = $(BASH) $(src)/compiling_cmds.sh rename_syms $< $@

# The pKVM hypervisor should be self-contained. All the symbols it uses should
# be implemented in its own text. Remove ftrace to prevent compiler to insert
# the __fentry__ symbols which are not part of the pKVM hypervisor text to
# simplify the implementation.
#
# NOTE: do not remove CC_FLAGS_CFI. Since CFI code chunks don't depend
# on the host kernel's global data, we can keep CFI coverage enabled
# for the hypervisor as well, and we _should_ keep it enabled, for the
# following reasons (apart from its security advantages):
# 1. To avoid problems with the boot time kernel patching which assumes
#    that if CFI is enabled, it covers the entire kernel text (see
#    apply_seal_endbr()).
# 2. To keep the calling convention compatible in cases when hypervisor
#    functions are called from host kernel code (before deprivilege).
KBUILD_CFLAGS := $(filter-out $(CC_FLAGS_FTRACE), $(KBUILD_CFLAGS))
