/* SPDX-License-Identifier: GPL-2.0 */
#if !defined(PKVM_HC)
BUILD_BUG_ON(1)
#endif

/* Hypercalls used only during pKVM initialization */
PKVM_HC(init_finalize)
PKVM_HC(commit_finalize)
PKVM_HC(reprivilege_cpu)

/* KVM ops */
PKVM_HC(enable_virtualization_cpu)
PKVM_HC(disable_virtualization_cpu)
PKVM_HC(check_processor_compatibility)
PKVM_HC(vm_init)
PKVM_HC(vm_finalize)
PKVM_HC(vm_destroy)
PKVM_HC(vcpu_create)
PKVM_HC(vcpu_free)
PKVM_HC(vcpu_reset)
PKVM_HC(vcpu_load)
PKVM_HC(vcpu_put)
PKVM_HC(vcpu_run)
PKVM_HC(vcpu_after_set_cpuid)
PKVM_HC(get_segment_base)
PKVM_HC(get_segment)
PKVM_HC(set_segment)
PKVM_HC(set_cr0)
PKVM_HC(set_cr4)
PKVM_HC(set_msr)
PKVM_HC(get_msr)
PKVM_HC(set_efer)
PKVM_HC(get_idt)
PKVM_HC(set_idt)
PKVM_HC(get_gdt)
PKVM_HC(set_gdt)
PKVM_HC(set_dr7)
PKVM_HC(get_rflags)
PKVM_HC(set_rflags)
PKVM_HC(flush_tlb_all)
PKVM_HC(flush_tlb_current)
PKVM_HC(flush_tlb_gva)
PKVM_HC(flush_tlb_guest)
PKVM_HC(set_interrupt_shadow)
PKVM_HC(get_interrupt_shadow)
PKVM_HC(complete_emulated_msr)
PKVM_HC(interrupt_allowed)
PKVM_HC(nmi_allowed)
PKVM_HC(inject_irq)
PKVM_HC(inject_nmi)
PKVM_HC(inject_exception)
PKVM_HC(cancel_injection)
PKVM_HC(get_nmi_mask)
PKVM_HC(set_nmi_mask)
PKVM_HC(enable_nmi_window)
PKVM_HC(enable_irq_window)
PKVM_HC(update_cr8_intercept)
PKVM_HC(set_virtual_apic_mode)
PKVM_HC(refresh_apicv_exec_ctrl)
PKVM_HC(load_eoi_exitmap)
PKVM_HC(hwapic_irr_update)
PKVM_HC(hwapic_isr_update)
PKVM_HC(write_tsc_offset)
PKVM_HC(write_tsc_multiplier)
PKVM_HC(post_set_cr3)
PKVM_HC(load_mmu_pgd)
PKVM_HC(setup_mce)
PKVM_HC(cache_reg)
PKVM_HC(update_cpuid_runtime)
PKVM_HC(update_exception_bitmap)
PKVM_HC(vcpu_add_fpstate)
PKVM_HC(host_share_hyp)
PKVM_HC(host_unshare_hyp)

/* KVM MMU hypercalls */
PKVM_HC(vm_mmu_map)
PKVM_HC(vm_mmu_unmap)
PKVM_HC(vm_mmu_age)

/* IOMMU driver hypercalls */
PKVM_HC(iommu_mmio_access)

/* pKVM vmexit tracing/profiling */
PKVM_HC(set_vmexit_trace)
PKVM_HC(dump_vmexit_trace)

/* Deprecated */
PKVM_HC(add_ptdev)

#undef PKVM_HC
